type AuthPayload {
    accessToken: String!
    refreshToken: String!
}

type User {
    username: String!
    email: String!
    firstName: String!
    lastName: String!
}

type Query {
    currentUser: User!
}

type Mutation {
    login(username: String!, password: String!): AuthPayload!
    register(
        username: String!
        email: String!
        password: String!
        confirmPassword: String!
        firstName: String!
        lastName: String!
    ): AuthPayload!
    refresh(refreshToken: String!): AuthPayload!
    ftueComplete(artworkIds: [Int!]!, genreIds: [ID!]!, artistIds: [Int!]!): Boolean!
    changeEmail(newEmail: String!): User!
    changePassword(oldPassword: String!, newPassword: String!): User!
    changeName(newFirstName: String!, newLastName: String!): User!
    deleteUser(username: String!): Boolean!
}
